

  const crops = [
    {
      name: "Wheat",
      quantity: 100,
      price: 2200,
      buyer: "AgroMart Pvt Ltd",
      location: "Lucknow, UP",
      contact: "9998887771"
    },
    {
      name: "Rice",
      quantity: 150,
      price: 2400,
      buyer: "GreenField Traders",
      location: "Karnal, Haryana",
      contact: "8887776661"
    },
    {
      name: "Wheat",
      quantity: 200,
      price: 2400,
      buyer: "AgriMart Pvt Ltd",
      location: "Noida, UP",
      contact: "9998887781"
    },
    {
      name: "Maize",
      quantity: 75,
      price: 2000,
      buyer: "CropBuy India",
      location: "Meerut, UP",
      contact: "7776665551"
    }, 
     {
      name: "Wheat",
      quantity: 250,
      price: 2450,
      buyer: "AgriHub Pvt Ltd",
      location: "Hapur, UP",
      contact: "9698887981"
    },
    {
      name: "Barley",
      quantity: 90,
      price: 2100,
      buyer: "Krishi Ventures",
      location: "Rohtak, Haryana",
      contact: "9876543210"
    },
    {
      name: "Wheat",
      quantity: 300,
      price: 2350,
      buyer: "Aakash Krishi Pvt Ltd",
      location: "Meerut, UP",
      contact: "9988887981"
    },
    {
      name: "Sugarcane",
      quantity: 120,
      price: 1800,
      buyer: "SweetAgro Ltd",
      location: "Sonipat, Haryana",
      contact: "9812345678"
    },{
      name: "Wheat",
      quantity: 300,
      price: 2350,
      buyer: "Aakash KrishiAgri Pvt Ltd",
      location: "Khurja, UP",
      contact: "9987887981"
    },
    {
      name: "Wheat",
      quantity: 120,
      price: 2300,
      buyer: "Bharat Agro Mart",
      location: "Lucknow, UP",
      contact: "9988776655"
    },
    {'name': 'Pulses',
      'quantity': 335,
      'price': 2656,
      'buyer': 'Agro India Ltd',
      'location': 'Sonipat, MP',
      'contact': '9604861392'},
     {'name': 'Barley',
      'quantity': 492,
      'price': 2132,
      'buyer': 'Kisan Mandal',
      'location': 'Faridabad, Punjab',
      'contact': '9733683399'},
     {'name': 'Pulses',
      'quantity': 411,
      'price': 1866,
      'buyer': 'Crop Mart',
      'location': 'Noida, Punjab',
      'contact': '9606661210'},
     {'name': 'Lentils',
      'quantity': 122,
      'price': 2598,
      'buyer': 'GreenHarvest Corp',
      'location': 'Bareilly, Punjab',
      'contact': '9350187978'},
     {'name': 'Mustard',
      'quantity': 197,
      'price': 2687,
      'buyer': 'Crop Mart',
      'location': 'Karnal, UP',
      'contact': '9386946885'},
     {'name': 'Rice',
      'quantity': 474,
      'price': 2471,
      'buyer': 'Annadata Traders',
      'location': 'Varanasi, Rajasthan',
      'contact': '9437266176'},
     {'name': 'Rice',
      'quantity': 229,
      'price': 2383,
      'buyer': 'Bharat Krishi Pvt Ltd',
      'location': 'Bhiwani, MP',
      'contact': '9511768804'},
     {'name': 'Barley',
      'quantity': 165,
      'price': 2621,
      'buyer': 'GreenHarvest Corp',
      'location': 'Rohtak, Haryana',
      'contact': '9277809890'},
     {'name': 'Barley',
      'quantity': 203,
      'price': 2269,
      'buyer': 'GreenHarvest Corp',
      'location': 'Aligarh, Rajasthan',
      'contact': '9342682850'},
     {'name': 'Rice',
      'quantity': 450,
      'price': 2498,
      'buyer': 'FarmFresh India',
      'location': 'Delhi, Punjab',
      'contact': '9943997771'},
     {'name': 'Millet',
      'quantity': 409,
      'price': 2321,
      'buyer': 'Agro India Ltd',
      'location': 'Bhiwani, Delhi',
      'contact': '9492229407'},
     {'name': 'Pulses',
      'quantity': 314,
      'price': 2497,
      'buyer': 'FarmFresh India',
      'location': 'Sonipat, Delhi',
      'contact': '9256386153'},
     {'name': 'Soybean',
      'quantity': 390,
      'price': 2216,
      'buyer': 'Khet Se Bazaar',
      'location': 'Meerut, MP',
      'contact': '9649030418'},
     {'name': 'Rice',
      'quantity': 129,
      'price': 1844,
      'buyer': 'Kisan Mandal',
      'location': 'Karnal, Haryana',
      'contact': '9255487410'},
     {'name': 'Pulses',
      'quantity': 374,
      'price': 2073,
      'buyer': 'GreenHarvest Corp',
      'location': 'Ambala, Rajasthan',
      'contact': '9336785036'},
     {'name': 'Barley',
      'quantity': 399,
      'price': 2358,
      'buyer': 'Bharat Krishi Pvt Ltd',
      'location': 'Noida, Delhi',
      'contact': '9281832553'},
     {'name': 'Sugarcane',
      'quantity': 310,
      'price': 2039,
      'buyer': 'Crop Mart',
      'location': 'Varanasi, Rajasthan',
      'contact': '9854194807'},
     {'name': 'Pulses',
      'quantity': 279,
      'price': 1842,
      'buyer': 'FarmFresh India',
      'location': 'Noida, Delhi',
      'contact': '9742316174'},
     {'name': 'Maize',
      'quantity': 343,
      'price': 2491,
      'buyer': 'Agro India Ltd',
      'location': 'Bareilly, Punjab',
      'contact': '9558294873'},
     {'name': 'Soybean',
      'quantity': 212,
      'price': 2728,
      'buyer': 'Agro India Ltd',
      'location': 'Ambala, Rajasthan',
      'contact': '9340802414'},
     {'name': 'Sugarcane',
      'quantity': 235,
      'price': 2552,
      'buyer': 'FarmFresh India',
      'location': 'Faridabad, MP',
      'contact': '9364514383'},
     {'name': 'Barley',
      'quantity': 220,
      'price': 2547,
      'buyer': 'Khet Se Bazaar',
      'location': 'Rohtak, Delhi',
      'contact': '9666047092'},
     {'name': 'Pulses',
      'quantity': 362,
      'price': 1972,
      'buyer': 'Khet Se Bazaar',
      'location': 'Noida, MP',
      'contact': '9743609243'},
     {'name': 'Maize',
      'quantity': 451,
      'price': 1967,
      'buyer': 'Gramin Agro Services',
      'location': 'Ambala, UP',
      'contact': '9583141263'},
     {'name': 'Millet',
      'quantity': 474,
      'price': 2361,
      'buyer': 'Agro India Ltd',
      'location': 'Varanasi, Haryana',
      'contact': '9636814660'},
     {'name': 'Mustard',
      'quantity': 238,
      'price': 2375,
      'buyer': 'Agro India Ltd',
      'location': 'Ambala, UP',
      'contact': '9210790430'},
     {'name': 'Millet',
      'quantity': 258,
      'price': 2089,
      'buyer': 'Gramin Agro Services',
      'location': 'Bareilly, Punjab',
      'contact': '9411132287'},
     {'name': 'Millet',
      'quantity': 498,
      'price': 2633,
      'buyer': 'Gramin Agro Services',
      'location': 'Kanpur, Haryana',
      'contact': '9629480685'},
     {'name': 'Mustard',
      'quantity': 462,
      'price': 1818,
      'buyer': 'Bharat Krishi Pvt Ltd',
      'location': 'Aligarh, MP',
      'contact': '9615249643'},
     {'name': 'Lentils',
      'quantity': 151,
      'price': 1989,
      'buyer': 'Kisan Mandal',
      'location': 'Agra, Haryana',
      'contact': '9860090478'},
     {'name': 'Sugarcane',
      'quantity': 314,
      'price': 1833,
      'buyer': 'Bharat Krishi Pvt Ltd',
      'location': 'Faridabad, Rajasthan',
      'contact': '9380603603'},
     {'name': 'Mustard',
      'quantity': 257,
      'price': 2056,
      'buyer': 'Crop Mart',
      'location': 'Jhansi, Haryana',
      'contact': '9463211228'},
     {'name': 'Sugarcane',
      'quantity': 394,
      'price': 1821,
      'buyer': 'GreenHarvest Corp',
      'location': 'Delhi, Delhi',
      'contact': '9809949000'},
     {'name': 'Pulses',
      'quantity': 384,
      'price': 1813,
      'buyer': 'Khet Se Bazaar',
      'location': 'Gurgaon, Haryana',
      'contact': '9528531945'},
     {'name': 'Pulses',
      'quantity': 229,
      'price': 1848,
      'buyer': 'Khet Se Bazaar',
      'location': 'Gurgaon, UP',
      'contact': '9867465444'},
     {'name': 'Soybean',
      'quantity': 253,
      'price': 2300,
      'buyer': 'GreenHarvest Corp',
      'location': 'Delhi, Delhi',
      'contact': '9257682148'},
     {'name': 'Soybean',
      'quantity': 116,
      'price': 2564,
      'buyer': 'Annadata Traders',
      'location': 'Varanasi, MP',
      'contact': '9954570862'},
     {'name': 'Barley',
      'quantity': 358,
      'price': 2166,
      'buyer': 'Desh Ki Krishi',
      'location': 'Delhi, Delhi',
      'contact': '9768519692'},
     {'name': 'Lentils',
      'quantity': 164,
      'price': 2252,
      'buyer': 'Annadata Traders',
      'location': 'Ambala, Haryana',
      'contact': '9912479038'},
     {'name': 'Millet',
      'quantity': 361,
      'price': 2078,
      'buyer': 'Annadata Traders',
      'location': 'Gurgaon, Punjab',
      'contact': '9259110166'},
     {'name': 'Millet',
      'quantity': 272,
      'price': 2323,
      'buyer': 'Kisan Mandal',
      'location': 'Gurgaon, Rajasthan',
      'contact': '9731706830'},
     {'name': 'Pulses',
      'quantity': 450,
      'price': 2095,
      'buyer': 'GreenHarvest Corp',
      'location': 'Gorakhpur, Punjab',
      'contact': '9478545287'},
     {'name': 'Soybean',
      'quantity': 277,
      'price': 1872,
      'buyer': 'Desh Ki Krishi',
      'location': 'Ambala, UP',
      'contact': '9596711393'},
     {'name': 'Pulses',
      'quantity': 145,
      'price': 2447,
      'buyer': 'Crop Mart',
      'location': 'Noida, UP',
      'contact': '9871780240'},
     {'name': 'Rice',
      'quantity': 121,
      'price': 2474,
      'buyer': 'GreenHarvest Corp',
      'location': 'Rohtak, Haryana',
      'contact': '9763502720'},
     {'name': 'Lentils',
      'quantity': 308,
      'price': 2381,
      'buyer': 'Agro India Ltd',
      'location': 'Lucknow, UP',
      'contact': '9308160612'},
     {'name': 'Sugarcane',
      'quantity': 405,
      'price': 2577,
      'buyer': 'Agro India Ltd',
      'location': 'Ambala, UP',
      'contact': '9849099612'},
     {'name': 'Rice',
      'quantity': 172,
      'price': 2627,
      'buyer': 'Gramin Agro Services',
      'location': 'Agra, Rajasthan',
      'contact': '9996893564'},
     {'name': 'Mustard',
      'quantity': 273,
      'price': 2230,
      'buyer': 'Crop Mart',
      'location': 'Gorakhpur, Delhi',
      'contact': '9295618738'},
     {'name': 'Millet',
      'quantity': 313,
      'price': 2710,
      'buyer': 'Gramin Agro Services',
      'location': 'Meerut, Haryana',
      'contact': '9214940552'},
    {
      name: "Rice",
      quantity: 250,
      price: 2400,
      buyer: "GreenField Traders",
      location: "Karnal, Haryana",
      contact: "8887776661"
    },
    {
      name: "Maize",
      quantity: 200,
      price: 2100,
      buyer: "CropBuy India",
      location: "Gorakhpur, UP",
      contact: "7776665552"
    },
    {
      name: "Sugarcane",
      quantity: 400,
      price: 1850,
      buyer: "SweetAgro Ltd",
      location: "Sonipat, Haryana",
      contact: "9812345678"
    },
    {
      name: "Barley",
      quantity: 180,
      price: 2150,
      buyer: "Krishi Ventures",
      location: "Rohtak, Haryana",
      contact: "9876543210"
    },
    {
      name: "Soybean",
      quantity: 320,
      price: 2700,
      buyer: "Agro India Ltd",
      location: "Bhopal, MP",
      contact: "9001122334"
    },
    {
      name: "Wheat",
      quantity: 500,
      price: 2375,
      buyer: "Desh Ki Krishi",
      location: "Agra, UP",
      contact: "9900112233"
    },
    {
      name: "Maize",
      quantity: 150,
      price: 2050,
      buyer: "Harvest India",
      location: "Hisar, Haryana",
      contact: "9191919191"
    },
    {
      name: "Rice",
      quantity: 300,
      price: 2425,
      buyer: "Kisan Mandal Pvt Ltd",
      location: "Amritsar, Punjab",
      contact: "9123456789"
    },  {
      name: "Wheat",
      quantity: 150,
      price: 2400,
      buyer: "Noida Agro Mart",
      location: "Noida, UP",
      contact: "9876543210"
    },
    {
      name: "Rice",
      quantity: 200,
      price: 2150,
      buyer: "Bulandshahr Grain Traders",
      location: "Bulandshahr, UP",
      contact: "9823456789"
    },
    {
      name: "Sugarcane",
      quantity: 500,
      price: 310,
      buyer: "Khurja Sweet Farms",
      location: "Khurja, UP",
      contact: "9812345678"
    },
    {
      name: "Maize",
      quantity: 180,
      price: 1950,
      buyer: "Meerut Corn Hub",
      location: "Meerut, UP",
      contact: "9898989898"
    },
    {
      name: "Barley",
      quantity: 100,
      price: 1900,
      buyer: "Aligarh Agro Market",
      location: "Aligarh, UP",
      contact: "9900112233"
    },
    {
      name: "Mustard",
      quantity: 140,
      price: 4950,
      buyer: "Hapur Mustard Traders",
      location: "Hapur, UP",
      contact: "9977665544"
    }
  
    // Add more crop entries as needed
  ];

  const container = document.getElementById('cropContainer');

  function displayCrops(data) {
    container.innerHTML = "";
    data.forEach(crop => {
      container.innerHTML += `
        <div class="crop-card">
          <h3>${crop.name}</h3>
          <p><strong>Quantity:</strong> ${crop.quantity} quintals</p>
          <p><strong>Price:</strong> ₹${crop.price}/quintal</p>
          <p><strong>Buyer:</strong> ${crop.buyer}</p>
          <p><strong>Location:</strong> ${crop.location}</p>
          <p><strong>Contact:</strong> ${crop.contact}</p>
          <div class="buttons">
            <button class="call-btn" onclick="callBuyer('${crop.contact}')">Call</button>
            <button class="msg-btn" onclick="messageBuyer('${crop.contact}')">Message</button>
          </div>
        </div>
      `;
    });
  }

  function filterCrops() {
    const query = document.getElementById('search').value.toLowerCase();
    const filtered = crops.filter(crop =>
      crop.name.toLowerCase().includes(query) ||
      crop.location.toLowerCase().includes(query)
    );
    displayCrops(filtered);
  }

  function callBuyer(number) {
    alert("Calling " + number);
  }

  function messageBuyer(number) {
    alert("Messaging " + number);
  }

  // Initial load
  displayCrops(crops);
